updated docs/readme, deployment readme, and individual service readme files
chinmayic/ODIM pull request #5
Opened 2020-10-20 10:12 UTC by chinmayic

**Service-wise individual readme files:**
1. Formatting and semantic changes
2. Added connection methods content in svc-aggregation/Readme

**Deployment Readme file:**
Semantic changes

**docs/Readme file:**
1. Added connection methods content.
2. Updated list of APIs.
3. Added TOC for connection methods content.

2020-10-20 14:54 UTC, irappa-pattar requested changes
Please address the following comments.

This PR doesn't have the story number and also it looks like it has multiple story changes.

2020-10-20 14:54 UTC, irappa-pattar commented on docs/README.md
> +         "@odata.id":"/redfish/v1/AggregationService/ConnectionMethods/76a7ec10-6629-499b-99ad-c77656e5a928"
if you are using uuid, use it across the connection method information otherwise use `connectionmethodsID`

2020-10-20 14:54 UTC, irappa-pattar commented on docs/README.md
> +            "@odata.id":"/redfish/v1/AggregationService/AggregationSources/{AggregationSourceId}"
Can be named as {AggregationSourceId1} and {AggregationSourceId2}

2020-10-21 07:55 UTC, rahulroshan-kachchap requested changes

2020-10-21 07:55 UTC, rahulroshan-kachchap commented on README.md
> +    These users are created on both the VM and the containers for the resource aggregator and the plugin. Ensure not to create them again.
User Id "odimra" & Group Id "1234" will be created on the VM and in the odimra container.
User Id "plugin" & Group Id "1235" will be created on the VM and in the grfplugin container.
Ensure  these User Id & Group Id are not present on the VM before deploying ODIMRA.

2020-10-21 07:55 UTC, rahulroshan-kachchap commented on README.md
> +  - The following users are created and added to group Ids automatically during deployment.
The following users are created and added to group Ids during certificate generation procedure.

2020-10-21 08:24 UTC, nimmalagautam approved these changes
i can see the odimra user creation updated
Ensure not to create `odimra` user during the installation of the VM.

2020-10-22 07:17 UTC, rahulroshan-kachchap approved these changes

2020-10-22 07:20 UTC, irappa-pattar approved these changes

2020-10-27 06:03 UTC, rahulroshan-kachchap requested changes

2020-10-27 06:03 UTC, rahulroshan-kachchap commented on docs/README.md
> +To access the base URL using a REST client, use IP address of the system where the resource aggregator is installed as `{odim_host}`.
may be you can write like- Replace `{odimra_host}` in the URL with IP address of the system where the resource aggregator is installed

2020-10-27 06:03 UTC, rahulroshan-kachchap commented on docs/README.md
> +>**NOTE**: To use FQDN as `{odim_host}`, add the Resource Aggregator for ODIM server certificate to the browser where the REST client is launched.
change odim to odimra

2020-10-27 06:16 UTC, rahulroshan-kachchap approved these changes

2020-10-27 06:41 UTC, merged